using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PoissonSoft.BinanceApi.Contracts.Enums;
using PoissonSoft.BinanceApi.Contracts.Serialization;

namespace PoissonSoft.BinanceApi.Contracts.SpotAccount
{
    /// <summary>
    /// Request object used to cancel an active order
    /// </summary>
    public class CancelOrderRequest
    {
        /// <summary/>
        [JsonProperty("symbol")]
        public string Symbol { get; set; }

        /// <summary>
        /// Either orderId or origClientOrderId must be sent (optional)
        /// </summary>
        [JsonProperty("orderId")]
        public long? OrderId { get; set; }

        /// <summary>
        /// Either orderId or origClientOrderId must be sent (optional)
        /// </summary>
        [JsonProperty("origClientOrderId")]
        public string OriginalClientOrderId { get; set; }

        /// <summary>
        /// Used to uniquely identify this cancel. Automatically generated by default. (optional)
        /// </summary>
        [JsonProperty("newClientOrderId")]
        public string NewClientOrderId { get; set; }

    }


}
